[package]
name = "md_editor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
gpui.workspace = true
md_buffer.workspace = true
md_text.workspace = true
markdown_wysiwyg.workspace = true
md_theme.workspace = true
md_assets.workspace = true
md_settings.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
