[package]
name = "markdown_syntax_bench"
version = "0.1.0"
publish = false
edition = "2024"
license = "Apache-2.0"

[workspace]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(perf_enabled)'] }

[dependencies]
markdown_wysiwyg = { path = "../../crates/markdown_wysiwyg" }
pulldown-cmark = "0.13.4"
