[package]
name = "markdown_wysiwyg"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/markdown_wysiwyg.rs"
doctest = false

[dependencies]
tree-sitter.workspace = true
tree-sitter-md.workspace = true

[dev-dependencies]
